services:
  redis:
    image: 'redis'
    ports:
      - '6379'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=hubroot'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
